//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTDownloader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_mk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_mk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YTDownloader.language_mk", typeof(language_mk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активност.
        /// </summary>
        internal static string activityTab {
            get {
                return ResourceManager.GetString("activityTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматска надградба.
        /// </summary>
        internal static string AutoUpdateFormText {
            get {
                return ResourceManager.GetString("AutoUpdateFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Најдобриот достапен.
        /// </summary>
        internal static string best {
            get {
                return ResourceManager.GetString("best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Симни.
        /// </summary>
        internal static string btnDownload {
            get {
                return ResourceManager.GetString("btnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залепи URL.
        /// </summary>
        internal static string btnPaste {
            get {
                return ResourceManager.GetString("btnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеото.
        /// </summary>
        internal static string btnVideoOnly {
            get {
                return ResourceManager.GetString("btnVideoOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целата плејлиста.
        /// </summary>
        internal static string btnWholePlaylist {
            get {
                return ResourceManager.GetString("btnWholePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форсирај 60p.
        /// </summary>
        internal static string cb60fps {
            get {
                return ResourceManager.GetString("cb60fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избриши од активност.
        /// </summary>
        internal static string cmDeleteActivity {
            get {
                return ResourceManager.GetString("cmDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избриши го фајлот од компјутер.
        /// </summary>
        internal static string cmDeleteFile {
            get {
                return ResourceManager.GetString("cmDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отворете ја папката што го соддржи видеото.
        /// </summary>
        internal static string cmOpenFolder {
            get {
                return ResourceManager.GetString("cmOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паузирај симнување.
        /// </summary>
        internal static string cmPause {
            get {
                return ResourceManager.GetString("cmPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжи симнување.
        /// </summary>
        internal static string cmResume {
            get {
                return ResourceManager.GetString("cmResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почни симнување.
        /// </summary>
        internal static string cmStart {
            get {
                return ResourceManager.GetString("cmStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопри симнување.
        /// </summary>
        internal static string cmStop {
            get {
                return ResourceManager.GetString("cmStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избриши од активност.
        /// </summary>
        internal static string deleteFromActivity {
            get {
                return ResourceManager.GetString("deleteFromActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избриши го фајлот од компјутер.
        /// </summary>
        internal static string deleteFromPC {
            get {
                return ResourceManager.GetString("deleteFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Селектираниот директориум не постои. Ве молиме проверете го пред да симнете..
        /// </summary>
        internal static string directoryDoesntExist {
            get {
                return ResourceManager.GetString("directoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Симнување.
        /// </summary>
        internal static string downloadTab {
            get {
                return ResourceManager.GetString("downloadTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преостанато време.
        /// </summary>
        internal static string etaColumn {
            get {
                return ResourceManager.GetString("etaColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат.
        /// </summary>
        internal static string formatColumn {
            get {
                return ResourceManager.GetString("formatColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрати аудио.
        /// </summary>
        internal static string gbTrim {
            get {
                return ResourceManager.GetString("gbTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Јазик:.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одберете јазик.
        /// </summary>
        internal static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматско надградување....
        /// </summary>
        internal static string lblAutoUpdating {
            get {
                return ResourceManager.GetString("lblAutoUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да се смени ова поставување додека има активни симнувања..
        /// </summary>
        internal static string lblCannotChangeSetting {
            get {
                return ResourceManager.GetString("lblCannotChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ве молиме не ја затварајте програмата!.
        /// </summary>
        internal static string lblDoNotClose {
            get {
                return ResourceManager.GetString("lblDoNotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квалитет.
        /// </summary>
        internal static string lblDownloadQuality {
            get {
                return ResourceManager.GetString("lblDownloadQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ: Поставувањето на оваа вредност превисоко.
        /// </summary>
        internal static string lblDownloadsWarning1 {
            get {
                return ResourceManager.GetString("lblDownloadsWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to значително ќе ги наруши перформансите на вашиот компјутер!.
        /// </summary>
        internal static string lblDownloadsWarning2 {
            get {
                return ResourceManager.GetString("lblDownloadsWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крајно време.
        /// </summary>
        internal static string lblEndTime {
            get {
                return ResourceManager.GetString("lblEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залепете линк од Јутјуб видео или плејлиста кои сакате да ги симнете:.
        /// </summary>
        internal static string lblEnterUrl {
            get {
                return ResourceManager.GetString("lblEnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Овој прозорец ќе се затвори автоматски..
        /// </summary>
        internal static string lblItWillCloseAuto {
            get {
                return ResourceManager.GetString("lblItWillCloseAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рестартирајте ја програмата за поставувањата да имаат ефект..
        /// </summary>
        internal static string lblRestartProgram {
            get {
                return ResourceManager.GetString("lblRestartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Симнете во.
        /// </summary>
        internal static string lblSaveTo {
            get {
                return ResourceManager.GetString("lblSaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почетно време.
        /// </summary>
        internal static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставете го времето на 00:00:00 ако сакате да ја симнете целата песна..
        /// </summary>
        internal static string lblTrimInfo {
            get {
                return ResourceManager.GetString("lblTrimInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимален број на истовремени симнувања:.
        /// </summary>
        internal static string MaxSimDownLabel {
            get {
                return ResourceManager.GetString("MaxSimDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3.
        /// </summary>
        internal static string mp3 {
            get {
                return ResourceManager.GetString("mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фајлот &quot;.
        /// </summary>
        internal static string msgCouldntDeleteFile1 {
            get {
                return ResourceManager.GetString("msgCouldntDeleteFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; е во употреба и не можеше да биде избришан. Проверете ја вашата симнувачка папка за недовршени фајлови..
        /// </summary>
        internal static string msgCouldntDeleteFile2 {
            get {
                return ResourceManager.GetString("msgCouldntDeleteFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеото &quot;.
        /// </summary>
        internal static string msgFilesNotDeleted1 {
            get {
                return ResourceManager.GetString("msgFilesNotDeleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; не можеше да биде избришано. Избришете го мануелно од вашата симнувачка папка..
        /// </summary>
        internal static string msgFilesNotDeleted2 {
            get {
                return ResourceManager.GetString("msgFilesNotDeleted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеото &quot;.
        /// </summary>
        internal static string msgVideoAlreadyInActivityTab1 {
            get {
                return ResourceManager.GetString("msgVideoAlreadyInActivityTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; кое пробувате да го додадете веќе постои во Активност Табот. Ве молиме, избришете го пред повторно да го симнете..
        /// </summary>
        internal static string msgVideoAlreadyInActivityTab2 {
            get {
                return ResourceManager.GetString("msgVideoAlreadyInActivityTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отворете ја папката што го соддржи видеото.
        /// </summary>
        internal static string openContaining {
            get {
                return ResourceManager.GetString("openContaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Најдобриот достапен (60fps).
        /// </summary>
        internal static string p60 {
            get {
                return ResourceManager.GetString("p60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паузирај.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопрено.
        /// </summary>
        internal static string pbStatus_cancelled {
            get {
                return ResourceManager.GetString("pbStatus_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертирање.
        /// </summary>
        internal static string pbStatus_converting {
            get {
                return ResourceManager.GetString("pbStatus_converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завршено.
        /// </summary>
        internal static string pbStatus_done {
            get {
                return ResourceManager.GetString("pbStatus_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка.
        /// </summary>
        internal static string pbStatus_error {
            get {
                return ResourceManager.GetString("pbStatus_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчитување.
        /// </summary>
        internal static string pbStatus_loading {
            get {
                return ResourceManager.GetString("pbStatus_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спојување.
        /// </summary>
        internal static string pbStatus_muxing {
            get {
                return ResourceManager.GetString("pbStatus_muxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паузирано.
        /// </summary>
        internal static string pbStatus_paused {
            get {
                return ResourceManager.GetString("pbStatus_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плејлиста.
        /// </summary>
        internal static string playlist {
            get {
                return ResourceManager.GetString("playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео кое пробувате да го додадете во неговиот линк содржи и плејлиста. Дали сакавте да го симнете видеото или целата плејлиста?
        ///
        ///Напомена: Вашиот избор ќе важи за сите останати вакви линкови..
        /// </summary>
        internal static string playlistAndVideoText {
            get {
                return ResourceManager.GetString("playlistAndVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Се вчитува плејлистата.
        /// </summary>
        internal static string playlistStatus {
            get {
                return ResourceManager.GetString("playlistStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео со линк од плејлиста беше детектирано.
        /// </summary>
        internal static string PlaylistVideoForm {
            get {
                return ResourceManager.GetString("PlaylistVideoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Јутјуб Давнлодерот на Марко v1.0.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогрес.
        /// </summary>
        internal static string progressColumn {
            get {
                return ResourceManager.GetString("progressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставувања.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Големина.
        /// </summary>
        internal static string sizeColumn {
            get {
                return ResourceManager.GetString("sizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брзина.
        /// </summary>
        internal static string speedColumn {
            get {
                return ResourceManager.GetString("speedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завршено.
        /// </summary>
        internal static string status0 {
            get {
                return ResourceManager.GetString("status0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчитување податоци.
        /// </summary>
        internal static string status1 {
            get {
                return ResourceManager.GetString("status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеото е веќе симнато.
        /// </summary>
        internal static string status10 {
            get {
                return ResourceManager.GetString("status10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Се симнува видео.
        /// </summary>
        internal static string status2 {
            get {
                return ResourceManager.GetString("status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Се симнува аудио.
        /// </summary>
        internal static string status3 {
            get {
                return ResourceManager.GetString("status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка со форматот, се симнува најдобриот достапен.
        /// </summary>
        internal static string status4 {
            get {
                return ResourceManager.GetString("status4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Се спојува.
        /// </summary>
        internal static string status5 {
            get {
                return ResourceManager.GetString("status5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка.
        /// </summary>
        internal static string status6 {
            get {
                return ResourceManager.GetString("status6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Се конвертира во MP3.
        /// </summary>
        internal static string status7 {
            get {
                return ResourceManager.GetString("status7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопрено.
        /// </summary>
        internal static string status8 {
            get {
                return ResourceManager.GetString("status8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паузирано.
        /// </summary>
        internal static string status9 {
            get {
                return ResourceManager.GetString("status9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string statusColumn {
            get {
                return ResourceManager.GetString("statusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штиклирајте го ова поле ако сакате да се
        ///осигурате дека вашето видео ќе се симне
        ///во 60p. (доколку е достапно).
        /// </summary>
        internal static string ttForce60fps {
            get {
                return ResourceManager.GetString("ttForce60fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непознато.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string videoColumn {
            get {
                return ResourceManager.GetString("videoColumn", resourceCulture);
            }
        }
    }
}
