//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTDownloader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YTDownloader.language_en", typeof(language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string activityTab {
            get {
                return ResourceManager.GetString("activityTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Update.
        /// </summary>
        internal static string AutoUpdateFormText {
            get {
                return ResourceManager.GetString("AutoUpdateFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Available.
        /// </summary>
        internal static string best {
            get {
                return ResourceManager.GetString("best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string btnDownload {
            get {
                return ResourceManager.GetString("btnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste URL.
        /// </summary>
        internal static string btnPaste {
            get {
                return ResourceManager.GetString("btnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video.
        /// </summary>
        internal static string btnVideoOnly {
            get {
                return ResourceManager.GetString("btnVideoOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whole playlist.
        /// </summary>
        internal static string btnWholePlaylist {
            get {
                return ResourceManager.GetString("btnWholePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force 60p.
        /// </summary>
        internal static string cb60fps {
            get {
                return ResourceManager.GetString("cb60fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from activity tab.
        /// </summary>
        internal static string cmDeleteActivity {
            get {
                return ResourceManager.GetString("cmDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file from your computer.
        /// </summary>
        internal static string cmDeleteFile {
            get {
                return ResourceManager.GetString("cmDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        internal static string cmOpenFolder {
            get {
                return ResourceManager.GetString("cmOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause download.
        /// </summary>
        internal static string cmPause {
            get {
                return ResourceManager.GetString("cmPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume download.
        /// </summary>
        internal static string cmResume {
            get {
                return ResourceManager.GetString("cmResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download.
        /// </summary>
        internal static string cmStart {
            get {
                return ResourceManager.GetString("cmStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop download.
        /// </summary>
        internal static string cmStop {
            get {
                return ResourceManager.GetString("cmStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from activity tab.
        /// </summary>
        internal static string deleteFromActivity {
            get {
                return ResourceManager.GetString("deleteFromActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file from your computer.
        /// </summary>
        internal static string deleteFromPC {
            get {
                return ResourceManager.GetString("deleteFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory does not exist. Please check it before continuing..
        /// </summary>
        internal static string directoryDoesntExist {
            get {
                return ResourceManager.GetString("directoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string downloadTab {
            get {
                return ResourceManager.GetString("downloadTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA.
        /// </summary>
        internal static string etaColumn {
            get {
                return ResourceManager.GetString("etaColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string formatColumn {
            get {
                return ResourceManager.GetString("formatColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim audio.
        /// </summary>
        internal static string gbTrim {
            get {
                return ResourceManager.GetString("gbTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language.
        /// </summary>
        internal static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto updating...
        /// </summary>
        internal static string lblAutoUpdating {
            get {
                return ResourceManager.GetString("lblAutoUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change this setting while there are active downloads..
        /// </summary>
        internal static string lblCannotChangeSetting {
            get {
                return ResourceManager.GetString("lblCannotChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not close the program!.
        /// </summary>
        internal static string lblDoNotClose {
            get {
                return ResourceManager.GetString("lblDoNotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Quality.
        /// </summary>
        internal static string lblDownloadQuality {
            get {
                return ResourceManager.GetString("lblDownloadQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Settings this number too high will significantly.
        /// </summary>
        internal static string lblDownloadsWarning1 {
            get {
                return ResourceManager.GetString("lblDownloadsWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to affect your computer&apos;s performance!.
        /// </summary>
        internal static string lblDownloadsWarning2 {
            get {
                return ResourceManager.GetString("lblDownloadsWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string lblEndTime {
            get {
                return ResourceManager.GetString("lblEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste a YouTube video or playlist URL that you want to download:.
        /// </summary>
        internal static string lblEnterUrl {
            get {
                return ResourceManager.GetString("lblEnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This window will close automatically..
        /// </summary>
        internal static string lblItWillCloseAuto {
            get {
                return ResourceManager.GetString("lblItWillCloseAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program for changes to take effect..
        /// </summary>
        internal static string lblRestartProgram {
            get {
                return ResourceManager.GetString("lblRestartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To.
        /// </summary>
        internal static string lblSaveTo {
            get {
                return ResourceManager.GetString("lblSaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the time at 00:00:00 if you want to download the whole song..
        /// </summary>
        internal static string lblTrimInfo {
            get {
                return ResourceManager.GetString("lblTrimInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of simultaneous downloads:.
        /// </summary>
        internal static string MaxSimDownLabel {
            get {
                return ResourceManager.GetString("MaxSimDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp3.
        /// </summary>
        internal static string mp3 {
            get {
                return ResourceManager.GetString("mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;.
        /// </summary>
        internal static string msgCouldntDeleteFile1 {
            get {
                return ResourceManager.GetString("msgCouldntDeleteFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; is in use and couldn&apos;t be deleted. Check your downloads folder for unfinished files..
        /// </summary>
        internal static string msgCouldntDeleteFile2 {
            get {
                return ResourceManager.GetString("msgCouldntDeleteFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video &quot;.
        /// </summary>
        internal static string msgFilesNotDeleted1 {
            get {
                return ResourceManager.GetString("msgFilesNotDeleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; couldn&apos;t be deleted. Delete it manually from your downloads folder..
        /// </summary>
        internal static string msgFilesNotDeleted2 {
            get {
                return ResourceManager.GetString("msgFilesNotDeleted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video &quot;.
        /// </summary>
        internal static string msgVideoAlreadyInActivityTab1 {
            get {
                return ResourceManager.GetString("msgVideoAlreadyInActivityTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; you are trying to add already exists in the Activity Tab. Please remove it before downloading it again..
        /// </summary>
        internal static string msgVideoAlreadyInActivityTab2 {
            get {
                return ResourceManager.GetString("msgVideoAlreadyInActivityTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        internal static string openContaining {
            get {
                return ResourceManager.GetString("openContaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Available (60fps).
        /// </summary>
        internal static string p60 {
            get {
                return ResourceManager.GetString("p60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string pbStatus_cancelled {
            get {
                return ResourceManager.GetString("pbStatus_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting.
        /// </summary>
        internal static string pbStatus_converting {
            get {
                return ResourceManager.GetString("pbStatus_converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string pbStatus_done {
            get {
                return ResourceManager.GetString("pbStatus_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string pbStatus_error {
            get {
                return ResourceManager.GetString("pbStatus_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string pbStatus_loading {
            get {
                return ResourceManager.GetString("pbStatus_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muxing.
        /// </summary>
        internal static string pbStatus_muxing {
            get {
                return ResourceManager.GetString("pbStatus_muxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string pbStatus_paused {
            get {
                return ResourceManager.GetString("pbStatus_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string playlist {
            get {
                return ResourceManager.GetString("playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A video you are trying to add also has a playlist in it&apos;s link. Did you mean to download the video or the whole playlist?
        ///
        ///Note: Your choice here will apply to all the remaining video/playlist links..
        /// </summary>
        internal static string playlistAndVideoText {
            get {
                return ResourceManager.GetString("playlistAndVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading playlist.
        /// </summary>
        internal static string playlistStatus {
            get {
                return ResourceManager.GetString("playlistStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video with playlist link detected.
        /// </summary>
        internal static string PlaylistVideoForm {
            get {
                return ResourceManager.GetString("PlaylistVideoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marko&apos;s YouTube Downloader v1.0.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string progressColumn {
            get {
                return ResourceManager.GetString("progressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string sizeColumn {
            get {
                return ResourceManager.GetString("sizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string speedColumn {
            get {
                return ResourceManager.GetString("speedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string status0 {
            get {
                return ResourceManager.GetString("status0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading metadata.
        /// </summary>
        internal static string status1 {
            get {
                return ResourceManager.GetString("status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video has already been downloaded.
        /// </summary>
        internal static string status10 {
            get {
                return ResourceManager.GetString("status10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading video.
        /// </summary>
        internal static string status2 {
            get {
                return ResourceManager.GetString("status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading audio.
        /// </summary>
        internal static string status3 {
            get {
                return ResourceManager.GetString("status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format error, downloading best quality.
        /// </summary>
        internal static string status4 {
            get {
                return ResourceManager.GetString("status4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muxing.
        /// </summary>
        internal static string status5 {
            get {
                return ResourceManager.GetString("status5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string status6 {
            get {
                return ResourceManager.GetString("status6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting to MP3.
        /// </summary>
        internal static string status7 {
            get {
                return ResourceManager.GetString("status7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string status8 {
            get {
                return ResourceManager.GetString("status8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string status9 {
            get {
                return ResourceManager.GetString("status9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string statusColumn {
            get {
                return ResourceManager.GetString("statusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this box if you want to make sure that
        ///your video downloads in 60p. (if available).
        /// </summary>
        internal static string ttForce60fps {
            get {
                return ResourceManager.GetString("ttForce60fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string videoColumn {
            get {
                return ResourceManager.GetString("videoColumn", resourceCulture);
            }
        }
    }
}
